services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: my_user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"