spring:
  datasource:
    url: jdbc:postgresql://localhost:${pg.port:5432}/postgres
    username: my_user
    driver-class-name: org.postgresql.Driver
  flyway:
    table: schema_version
    enabled: true